[package]
name = "secrenv"
version = "0.1.0"
edition = "2021"
authors = ["Dave Williams <dave@dave.io>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
