name: ci

on:
  push:
    branches:
      - main
  pull_request: null

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: ruby-${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - 3.4.7

    steps:
      - uses: actions/checkout@v4
      - name: setup
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cargo-cache: true
          rubygems: 3.7.2
      - name: rake
        run: bundle exec rake
